### ISSUE TITLE
Issue #72 / PR #85 broke Jira projects that aren't at the root of their server

### ISSUE THREAD

**Issue by ewanmellor** [crashlytics/crashlytics-services#90]
Issue #72 / PR #85 has broken Crashlytics integration with my Jira project.  It is hosted at `https://my.example.com/jira/browse/XX`.  Since it is at `/jira` rather than the root, this is now broken.  This results in the verification step succeeding, but no Jira tickets ever get created.  A member of Crashlytics Support tells me that they are seeing 404 errors in their logs, which makes sense.

Before PR #85:

```
  def parse_url(url)
    uri = URI(url)
    result = { :url_prefix => url.match(/(https?:\/\/.*?)\/browse\//)[1],
      :project_key => uri.path.match(/\/browse\/(.+?)(\/|$)/)[1]}
    result
  end

> parse_url('https://my.example.com/jira/browse/XX')
=> {:url_prefix=>"https://my.example.com/jira", :project_key=>"XX"}
```

After PR #85:

```
  def parse_url(url)
    uri = URI(url)
    result = { :url_prefix => url.match(/(https?:\/\/.*?)\/.+\//)[1],
      :project_key => uri.path.match(/\/.+\/(.+?)(\/|$)/)[1]}
    result
  end

> parse_url('https://my.example.com/jira/browse/XX')
=> {:url_prefix=>"https://my.example.com", :project_key=>"XX"}
```

cc: @seandc @jladieu

**Comment by jladieu** [comment]
@ewanmellor Thank you so much for letting us know, and for your detailed steps to reproduce the issue, will take a look at this as soon as I can and keep this ticket updated with what we find

**Comment by jladieu** [comment]
@ewanmellor We deployed a potential fix for this -- do you want to give your integration a try and let us know how it works?

**Comment by ewanmellor** [comment]
@jladieu This still isn't working I'm afraid.

Looking at this bit of the change:

    resp = client.post("#{url_components[:url_prefix]}/rest/api/2/issue", post_body.to_json)

This URL needs to include `:context_path` and I'm guessing that JIRA::Client isn't doing that for you because this is a fully-qualified URL.

I notice later in the file that there's this code:

    client.post('/rest/webhooks/1.0/webhook', webhook_params.to_json)

So does that mean that the `url_prefix` isn't needed at all?  In other words, does JIRA::Client append the appropriate prefixes if they aren't specified?  Do you know why the `url_prefix` is in there in the first place?

I hope that one or other of these would work:

    resp = client.post('/rest/api/2/issue', post_body.to_json)

    resp = client.post("#{url_components[:url_prefix]}#{url_components[:context_path]}/rest/api/2/issue", post_body.to_json)

**Comment by jladieu** [comment]
Reopening this for further investigation, thanks for the help troubleshooting @ewanmellor !

**Comment by ewanmellor** [comment]
@jladieu I miss my Jira integration ;-(  Any progress here?  Thanks.

**Comment by mattmassicotte** [comment]
@ewanmellor ack. We've got this in our queue. Sorry for the trouble :(

**Comment by seandc** [comment]
@ewanmellor We just deployed a fix for the Jira integration.  Please let me know if it is working for you.

**Comment by ewanmellor** [comment]
@seandc The bad news is that my app just crashed ;-(  The good news is that the Jira hook is working again, thanks ;-)
